// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACE_YOUR_ANDROID_KEY_HERE',
    appId: '1:690020680586:android:952a9c966fffe0db5abe73',
    messagingSenderId: '690020680586',
    projectId: 'erestro-single-vender',
    storageBucket: 'erestro-single-vender.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACE_YOUR_IOS_KEY_HERE',
    appId: '1:690020680586:ios:7b9d9716a8acf1935abe73',
    messagingSenderId: '690020680586',
    projectId: 'erestro-single-vender',
    storageBucket: 'erestro-single-vender.firebasestorage.app',
    androidClientId:
        '690020680586-2akm4ddvavajokc8eadabupl3rkal30d.apps.googleusercontent.com',
    iosClientId:
        '690020680586-hrpobf0v084ohfcq2u5gvlasgcps064j.apps.googleusercontent.com',
    iosBundleId: 'com.wrteam.erestroSingleVenderRider',
  );
}
